#all augments are formatted in a specific way:
#<name (id) of augment>: ("phenomenal", etc.; DO NOT MAKE TWO THAT HAVE THE SAME NAME!)
#  armor/armor-toughness/attack-damage/attack-speed/knockback-resistance/luck-max-health/movement-speed: (you can add whatever of these attributes you want, but dont add the same attr twice; all zero/non-number values are ignored)
#    add: 0 (boosts stat by val; additive)
#    mult-add: 0 (boosts stat by 1+val; multiplicative, stacks additively with other mult-add)
#    mult-mult: 0 (boosts stat by 1+val; multiplicative, stacks multiplicatively with other mult-mult)
#  display-name: <name> (supports minecraft color codes; two can have the same display name but NOT THE SAME ID)
#  can-apply-to-armor/elytras/swords/axes/tridents/bows/crossbows/shields/tools: true/false (if it cant be applied, that gear wont get that trait)
# below are some examples!
augment-list:
  - phenomenal
  - stubborn
  - stalwart
  - sharp
  - unwieldy
  - swift
phenomenal:
  armor:
    add: 0
    mult-add: 0
    mult-mult: 0.5
  armor-toughness:
    add: 5
    mult-add: 0
    mult-mult: 0
  attack-damage:
    add: 0
    mult-add: 0
    mult-mult: 0.3
  attack-speed:
    add: 0
    mult-add: 0
    mult-mult: 0.25
  knockback-resistance:
    add: 0
    mult-add: 0
    mult-mult: 0.25
  luck:
    add: 0
    mult-add: 0
    mult-mult: 0.25
  max-health:
    add: 0
    mult-add: 0
    mult-mult: 1
  movement-speed:
    add: 0
    mult-add: 0
    mult-mult: 0.2
  display-name: §d§lPHENOMENAL
  can-apply-to-armor: true
  can-apply-to-elytras: true
  can-apply-to-swords: true
  can-apply-to-axes: true
  can-apply-to-tridents: true
  can-apply-to-bows: true
  can-apply-to-crossbows: true
  can-apply-to-shields: true
  can-apply-to-tools: true
stubborn:
  display-name: §a§lSTUBBORN
  knockback-resistance:
    add: 0.1
  can-apply-to-armor: true
  can-apply-to-shields: true
  weight: 20
stalwart:
  display-name: §a§lSTALWART
  knockback-resistance:
    add: 0.3
  can-apply-to-armor: true
  can-apply-to-shields: true
  weight: 5
sharp:
  display-name: §a§lSHARP
  attack-damage:
    mult-mult: 0.05
  can-apply-to-swords: true
  can-apply-to-axes: true
  can-apply-to-tridents: true
  weight: 20
unwieldy:
  display-name: §a§lUNWIELDY
  attack-speed:
    mult-mult: -0.5
  can-apply-to-swords: true
  can-apply-to-axes: true
  can-apply-to-tridents: true
  weight: 20
swift:
  display-name: §a§lSWIFT
  attack-speed:
    mult-mult: 0.5
  can-apply-to-swords: true
  can-apply-to-axes: true
  can-apply-to-tridents: true
  weight: 20