name: MagicMonsters
main: main.MagicMonsters
version: 1.0
api-version: 1.17
commands:
    warmode:
        description: Clears inventory and gives a diamond kit.
    augmentlist:
        description: List all loaded augments
